### PR TITLE
Fix incorrect behavior related to duplicate people

### LINKED ISSUE #131: [PE-D][Tester D] I can add identical person to the list
I can add totally identical person.

Expected to get an error message.

It may give us some unclear information when we are using find by name command. 

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: wallacexuhanxiao/ped#1

### LINKED ISSUE #132: [PE-D][Tester D] Pair conmmand is buggy with duplicated people
# before

# after

### Maybe fix the problem on duplicated person could help fix this bug?

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: wallacexuhanxiao/ped#2

### LINKED ISSUE #137: [PE-D][Tester D] Log does not updated immediately the edit command
# before

# after

## Expect the log to change the person's name upon edit command.

However, it will be updated in the next command. so it is considered low severity.
Maybe make the update instance is a better choice?

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: wallacexuhanxiao/ped#3

### LINKED ISSUE #178: [PE-D][Tester E] Unknown duplicate persons error message thrown
Interface output:

Terminal output:

This pairing throws an invalid command even though it should be valid, as seen in the screen shot message. I checked the terminal to see that there was an uncaught exception thrown. However, the pairing still works. 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: yleeyilin/ped#23

### PR DESCRIPTION
**Pull request by CJerrong**
There was previously incorrect behavior caused by the code incorrectly allowing duplicate people. Issues can be found at issues #178 and #132.

What this PR fixes:
Closes #178
Closes #132 
Closes #131 
Closes #137 

- Disallows adding of duplicate persons
- Disallow editing the name of an existing person into a name that is the same as another person currently in Elder Scrolls
- Currently Name comparisons are case sensitive so `David Li` == `David li`
- Fixed the incorrect behavior related to logs not updating after edit, showing incorrect information to the user

### CODE REVIEW

File: src/test/java/scrolls/elder/model/person/PersonTest.java [hunk 1]
```diff
@@ -41,10 +38,10 @@ public void isSamePerson() {
                         .withAddress(VALID_ADDRESS_BOB)
                         .withTags(VALID_TAG_HUSBAND)
                         .build();
-        Assertions.assertTrue(TypicalPersons.ALICE.isSamePerson(editedAlice));
+        Assertions.assertTrue(TypicalPersons.ALICE.isSameId(editedAlice));
 
         // different id, all other attributes same -> returns false
```
Comment (gerteck) [inline src/test/java/scrolls/elder/model/person/PersonTest.java]: Maybe change the comment to reflect the changed testcase

File: src/test/java/scrolls/elder/model/person/PersonTest.java [hunk 2]
```diff
@@ -41,10 +38,10 @@ public void isSamePerson() {
                         .withAddress(VALID_ADDRESS_BOB)
                         .withTags(VALID_TAG_HUSBAND)
                         .build();
-        Assertions.assertTrue(TypicalPersons.ALICE.isSamePerson(editedAlice));
+        Assertions.assertTrue(TypicalPersons.ALICE.isSameId(editedAlice));
 
-        // different id, all other attributes same -> returns false
-        editedAlice = new PersonBuilder(TypicalPersons.ALICE).withId(VALID_ID_BOB).build();
+        // different name, all other attributes same -> returns false
```
Comment (gerteck) [inline src/test/java/scrolls/elder/model/person/PersonTest.java:43]: 👍

**Review by gerteck — APPROVED** [review]
