### PR TITLE
Update Ui Class Diagram in DG and fix bug in logEdit and logDelete

### LINKED ISSUE #128: Fix IndexOutofBounds exception for LogEdit and LogDelete
- Exception occurs as the unique Id of a Person is passed into the parameter of the filtered Person list
- Should use find by Id or get from list by Index instead

### PR DESCRIPTION
**Pull request by CJerrong**
- Updated Ui class to reflect current UI structure
- Fixed bog in LogEdit and LogDelete classes which were calling lastShownPList.get(personId), which would result in out of bounds, if a person was deleted from the list and the greatest id is called. Refactored to use PersonStore.getPersonById(personId) instead

### CODE REVIEW

File: src/main/java/scrolls/elder/logic/commands/LogDeleteCommand.java [hunk 1]
```diff
@@ -75,8 +75,8 @@ public CommandResult execute(Model model) throws CommandException {
         int durationToDelete = logToDelete.getDuration();
 
         // Update the timeServed of the volunteer and befriendee
-        Person volunteer = lastShownPList.get(logToDelete.getVolunteerId());
-        Person befriendee = lastShownPList.get(logToDelete.getBefriendeeId());
+        Person volunteer = personStore.getPersonFromID(logToDelete.getVolunteerId());
```
Comment (gerteck) [inline src/main/java/scrolls/elder/logic/commands/LogDeleteCommand.java:78]: Nice bug squish! 👍

**Review by gerteck — APPROVED** [review]
LGTM
